-- =============================================
-- MS-INSPECCIONES: Secuencias, tablas e índices (Oracle 11g)
-- =============================================

-- Secuencias
CREATE SEQUENCE SEQ_INSPECCIONES START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PLAGAS       START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_RESULTADOS   START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;

-- -------------------------
-- Tabla T_INSPECCIONES
-- -------------------------
CREATE TABLE T_INSPECCIONES (
    ID_INSPECCION       NUMBER(19,0)   NOT NULL,
    ID_PREDIO           NUMBER(19,0)   NOT NULL,
    ID_ASISTENTE        NUMBER(19,0)   NOT NULL,
    FECHA_INSPECCION    DATE           NOT NULL,
    OBSERVACIONES       VARCHAR2(2000),
    ESTADO              VARCHAR2(20),
    FECHA_CREACION      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_INSPECCIONES       PRIMARY KEY (ID_INSPECCION),
    CONSTRAINT CHK_ESTADO_INSPECCION CHECK (ESTADO IN ('PENDIENTE','EN_PROCESO','COMPLETADA'))
);

CREATE INDEX IDX_INSPECCIONES_PREDIO    ON T_INSPECCIONES(ID_PREDIO);
CREATE INDEX IDX_INSPECCIONES_ASISTENTE ON T_INSPECCIONES(ID_ASISTENTE);
CREATE INDEX IDX_INSPECCIONES_FECHA     ON T_INSPECCIONES(FECHA_INSPECCION);

CREATE OR REPLACE TRIGGER TRG_INSPECCIONES_UPDATE
BEFORE UPDATE ON T_INSPECCIONES
FOR EACH ROW
BEGIN
    :NEW.FECHA_ACTUALIZACION := CURRENT_TIMESTAMP;
END;
/

-- -------------------------
-- Tabla T_PLAGAS
-- -------------------------
CREATE TABLE T_PLAGAS (
    ID_PLAGA              NUMBER(19,0)  NOT NULL,
    ID_INSPECCION         NUMBER(19,0)  NOT NULL,
    NOMBRE_PLAGA          VARCHAR2(100) NOT NULL,
    TIPO_PLAGA            VARCHAR2(50),
    SEVERIDAD             VARCHAR2(50),
    PORCENTAJE_AFECTACION NUMBER(5,2),
    FECHA_CREACION        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PLAGAS              PRIMARY KEY (ID_PLAGA),
    CONSTRAINT CHK_TIPO_PLAGA         CHECK (TIPO_PLAGA IN ('INSECTO','HONGO','BACTERIA','VIRUS','MALEZA')),
    CONSTRAINT CHK_PORCENTAJE_PLAGA   CHECK (PORCENTAJE_AFECTACION >= 0 AND PORCENTAJE_AFECTACION <= 100),
    CONSTRAINT FK_PLAGA_INSPECCION    FOREIGN KEY (ID_INSPECCION) REFERENCES T_INSPECCIONES(ID_INSPECCION) ON DELETE CASCADE
);

CREATE INDEX IDX_PLAGAS_INSPECCION ON T_PLAGAS(ID_INSPECCION);

-- -------------------------
-- Tabla T_RESULTADOS
-- -------------------------
CREATE TABLE T_RESULTADOS (
    ID_RESULTADO         NUMBER(19,0)   NOT NULL,
    ID_INSPECCION        NUMBER(19,0)   NOT NULL,
    RECOMENDACION        VARCHAR2(2000),
    TRATAMIENTO_SUGERIDO VARCHAR2(1000),
    FECHA_SEGUIMIENTO    DATE,
    ESTADO               VARCHAR2(20),
    FECHA_CREACION       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_RESULTADOS        PRIMARY KEY (ID_RESULTADO),
    CONSTRAINT CHK_ESTADO_RESULTADO CHECK (ESTADO IN ('PENDIENTE','EN_PROCESO','RESUELTO')),
    CONSTRAINT FK_RESULTADO_INSPECCION FOREIGN KEY (ID_INSPECCION) REFERENCES T_INSPECCIONES(ID_INSPECCION) ON DELETE CASCADE
);

CREATE INDEX IDX_RESULTADOS_INSPECCION ON T_RESULTADOS(ID_INSPECCION);

-- -------------------------
-- Datos de ejemplo
-- -------------------------
INSERT INTO T_INSPECCIONES (ID_INSPECCION, ID_PREDIO, ID_ASISTENTE, FECHA_INSPECCION, OBSERVACIONES, ESTADO)
VALUES (SEQ_INSPECCIONES.NEXTVAL, 1, 2, TRUNC(SYSDATE), 'Inspección regular mensual', 'PENDIENTE');

INSERT INTO T_PLAGAS (ID_PLAGA, ID_INSPECCION, NOMBRE_PLAGA, TIPO_PLAGA, SEVERIDAD, PORCENTAJE_AFECTACION)
VALUES (SEQ_PLAGAS.NEXTVAL, 1, 'Gusano Cogollero', 'INSECTO', 'MEDIA', 15.5);

INSERT INTO T_PLAGAS (ID_PLAGA, ID_INSPECCION, NOMBRE_PLAGA, TIPO_PLAGA, SEVERIDAD, PORCENTAJE_AFECTACION)
VALUES (SEQ_PLAGAS.NEXTVAL, 1, 'Roya del Maíz', 'HONGO', 'BAJA', 8.0);

INSERT INTO T_RESULTADOS (ID_RESULTADO, ID_INSPECCION, RECOMENDACION, TRATAMIENTO_SUGERIDO, ESTADO)
VALUES (SEQ_RESULTADOS.NEXTVAL, 1, 'Aplicar insecticida de bajo impacto', 'Cipermetrina 10% - Dosis: 1 L/Ha', 'PENDIENTE');

COMMIT;
