-- Script de inicialización para Oracle XE
-- Este script crea las secuencias necesarias para los microservicios

-- Conectar como SYSTEM
CONNECT system/oracle@localhost:1521/XE;

-- Crear secuencias para Usuarios
CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTORES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ASISTENTES START WITH 1 INCREMENT BY 1 NOCACHE;

-- Crear secuencias para Predios
CREATE SEQUENCE SEQ_MUNICIPIOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PREDIOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CULTIVOS START WITH 1 INCREMENT BY 1 NOCACHE;

-- Crear secuencias para Inspecciones
CREATE SEQUENCE SEQ_INSPECCIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PLAGAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESULTADOS START WITH 1 INCREMENT BY 1 NOCACHE;

COMMIT;
