-- =============================================
-- MS-USUARIOS: Secuencias, tablas e índices (Oracle 11g)
-- =============================================

-- Secuencias
CREATE SEQUENCE SEQ_USUARIOS    START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRODUCTORES START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_ASISTENTES  START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;

-- -------------------------
-- Tabla T_USUARIOS
-- -------------------------
CREATE TABLE T_USUARIOS (
    ID_USUARIO         NUMBER(19,0)  NOT NULL,
    NOMBRE             VARCHAR2(100) NOT NULL,
    EMAIL              VARCHAR2(100) NOT NULL,
    TELEFONO           VARCHAR2(20),
    TIPO_USUARIO       VARCHAR2(50)  NOT NULL,
    ESTADO             VARCHAR2(20)  NOT NULL,
    FECHA_CREACION     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USUARIOS       PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIOS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_TIPO_USUARIO  CHECK (TIPO_USUARIO IN ('PRODUCTOR','ASISTENTE_TECNICO','ADMIN')),
    CONSTRAINT CHK_ESTADO_USR    CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE INDEX IDX_USUARIOS_EMAIL ON T_USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIOS_TIPO  ON T_USUARIOS(TIPO_USUARIO);

CREATE OR REPLACE TRIGGER TRG_USUARIOS_UPDATE
BEFORE UPDATE ON T_USUARIOS
FOR EACH ROW
BEGIN
    :NEW.FECHA_ACTUALIZACION := CURRENT_TIMESTAMP;
END;
/

-- -------------------------
-- Tabla T_PRODUCTORES
-- -------------------------
CREATE TABLE T_PRODUCTORES (
    ID_PRODUCTOR     NUMBER(19,0)  NOT NULL,
    ID_USUARIO       NUMBER(19,0)  NOT NULL,
    CEDULA           VARCHAR2(20)  NOT NULL,
    RAZON_SOCIAL     VARCHAR2(150),
    NUMERO_HECTAREAS FLOAT,
    CERTIFICACIONES  VARCHAR2(255),
    CONSTRAINT PK_PRODUCTORES        PRIMARY KEY (ID_PRODUCTOR),
    CONSTRAINT UQ_PRODUCTORES_CEDULA UNIQUE (CEDULA)
);

-- -------------------------
-- Tabla T_ASISTENTES_TECNICOS
-- -------------------------
CREATE TABLE T_ASISTENTES_TECNICOS (
    ID_ASISTENTE    NUMBER(19,0) NOT NULL,
    ID_USUARIO      NUMBER(19,0) NOT NULL,
    CEDULA          VARCHAR2(20) NOT NULL,
    ESPECIALIDAD    VARCHAR2(100),
    NUMERO_LICENCIA VARCHAR2(50),
    ESTADO_LICENCIA VARCHAR2(20),
    CONSTRAINT PK_ASISTENTES          PRIMARY KEY (ID_ASISTENTE),
    CONSTRAINT UQ_ASISTENTES_CEDULA   UNIQUE (CEDULA),
    CONSTRAINT UQ_ASISTENTES_LICENCIA UNIQUE (NUMERO_LICENCIA)
);

-- -------------------------
-- Datos de ejemplo
-- -------------------------
INSERT INTO T_USUARIOS (ID_USUARIO, NOMBRE, EMAIL, TELEFONO, TIPO_USUARIO, ESTADO)
VALUES (SEQ_USUARIOS.NEXTVAL, 'Juan Pérez', 'juan@agro.com', '3101234567', 'PRODUCTOR', 'ACTIVO');

INSERT INTO T_USUARIOS (ID_USUARIO, NOMBRE, EMAIL, TELEFONO, TIPO_USUARIO, ESTADO)
VALUES (SEQ_USUARIOS.NEXTVAL, 'María García', 'maria@agro.com', '3107654321', 'ASISTENTE_TECNICO', 'ACTIVO');

INSERT INTO T_USUARIOS (ID_USUARIO, NOMBRE, EMAIL, TELEFONO, TIPO_USUARIO, ESTADO)
VALUES (SEQ_USUARIOS.NEXTVAL, 'Carlos López', 'carlos@agro.com', '3102345678', 'PRODUCTOR', 'ACTIVO');

COMMIT;
