-- =============================================
-- MS-TERRITORIAL: Secuencias, tablas e índices (Oracle 11g)
-- =============================================

-- Secuencias
CREATE SEQUENCE SEQ_MUNICIPIOS START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PREDIOS    START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CULTIVOS   START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;

-- -------------------------
-- Tabla T_MUNICIPIOS
-- -------------------------
CREATE TABLE T_MUNICIPIOS (
    ID_MUNICIPIO   NUMBER(19,0)  NOT NULL,
    NOMBRE         VARCHAR2(100) NOT NULL,
    DEPARTAMENTO   VARCHAR2(100),
    CODIGO_DANE    VARCHAR2(20),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MUNICIPIOS        PRIMARY KEY (ID_MUNICIPIO),
    CONSTRAINT UQ_MUNICIPIOS_NOMBRE UNIQUE (NOMBRE)
);

-- -------------------------
-- Tabla T_PREDIOS
-- -------------------------
CREATE TABLE T_PREDIOS (
    ID_PREDIO           NUMBER(19,0)   NOT NULL,
    ID_PRODUCTOR        NUMBER(19,0)   NOT NULL,
    NOMBRE              VARCHAR2(100)  NOT NULL,
    ID_MUNICIPIO        NUMBER(19,0)   NOT NULL,
    AREA_HECTAREAS      NUMBER(10,2)   NOT NULL,
    LATITUD             NUMBER(10,6),
    LONGITUD            NUMBER(10,6),
    ESTADO              VARCHAR2(20),
    FECHA_CREACION      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PREDIOS        PRIMARY KEY (ID_PREDIO),
    CONSTRAINT CHK_ESTADO_PREDIO CHECK (ESTADO IN ('ACTIVO','INACTIVO')),
    CONSTRAINT CHK_AREA_PREDIOS  CHECK (AREA_HECTAREAS > 0),
    CONSTRAINT FK_PREDIO_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES T_MUNICIPIOS(ID_MUNICIPIO)
);

CREATE INDEX IDX_PREDIOS_PRODUCTOR ON T_PREDIOS(ID_PRODUCTOR);
CREATE INDEX IDX_PREDIOS_MUNICIPIO ON T_PREDIOS(ID_MUNICIPIO);

CREATE OR REPLACE TRIGGER TRG_PREDIOS_UPDATE
BEFORE UPDATE ON T_PREDIOS
FOR EACH ROW
BEGIN
    :NEW.FECHA_ACTUALIZACION := CURRENT_TIMESTAMP;
END;
/

-- -------------------------
-- Tabla T_CULTIVOS
-- -------------------------
CREATE TABLE T_CULTIVOS (
    ID_CULTIVO             NUMBER(19,0) NOT NULL,
    ID_PREDIO              NUMBER(19,0) NOT NULL,
    TIPO_CULTIVO           VARCHAR2(100),
    AREA_HECTAREAS         NUMBER(10,2),
    FECHA_SIEMBRA          DATE,
    FECHA_COSECHA_ESTIMADA DATE,
    ESTADO                 VARCHAR2(20),
    FECHA_CREACION         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CULTIVOS        PRIMARY KEY (ID_CULTIVO),
    CONSTRAINT CHK_ESTADO_CULTIVO CHECK (ESTADO IN ('SIEMBRA','CRECIMIENTO','COSECHA','RECOLECCION')),
    CONSTRAINT FK_CULTIVO_PREDIO  FOREIGN KEY (ID_PREDIO) REFERENCES T_PREDIOS(ID_PREDIO) ON DELETE CASCADE
);

CREATE INDEX IDX_CULTIVOS_PREDIO ON T_CULTIVOS(ID_PREDIO);

-- -------------------------
-- Datos de ejemplo
-- -------------------------
INSERT INTO T_MUNICIPIOS (ID_MUNICIPIO, NOMBRE, DEPARTAMENTO, CODIGO_DANE)
VALUES (SEQ_MUNICIPIOS.NEXTVAL, 'Bucaramanga', 'Santander', '68001');

INSERT INTO T_MUNICIPIOS (ID_MUNICIPIO, NOMBRE, DEPARTAMENTO, CODIGO_DANE)
VALUES (SEQ_MUNICIPIOS.NEXTVAL, 'Floridablanca', 'Santander', '68088');

INSERT INTO T_MUNICIPIOS (ID_MUNICIPIO, NOMBRE, DEPARTAMENTO, CODIGO_DANE)
VALUES (SEQ_MUNICIPIOS.NEXTVAL, 'Girón', 'Santander', '68092');

INSERT INTO T_PREDIOS (ID_PREDIO, ID_PRODUCTOR, NOMBRE, ID_MUNICIPIO, AREA_HECTAREAS, LATITUD, LONGITUD, ESTADO)
VALUES (SEQ_PREDIOS.NEXTVAL, 1, 'Finca El Descanso', 1, 25.5, 7.1289, -73.1156, 'ACTIVO');

INSERT INTO T_PREDIOS (ID_PREDIO, ID_PRODUCTOR, NOMBRE, ID_MUNICIPIO, AREA_HECTAREAS, LATITUD, LONGITUD, ESTADO)
VALUES (SEQ_PREDIOS.NEXTVAL, 1, 'Finca Las Colinas', 2, 15.8, 7.0642, -73.1652, 'ACTIVO');

COMMIT;
